### ISSUE TITLE
[FEAT] 프로필 정보 수정 API 구현 

### ISSUE THREAD

**Issue by unanchoi** [Katchup-dev/Katchup-server#142]
## 🥫 Issue 🥫

- 프로필 정보 수정 API를 구현합니다.

## 🍔  Todo 🥤
- [ ] 프로필 정보 수정 API

## 논의사항

프로필 사진 변경을 위해 AWS S3를 사용해야 할 것 같은데요.

`implementation 'org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE'`

현재 저희가 S3를 사용하기 위해서 위 라이브러리를 사용하고 있는데, 해당 라이브러리가 업데이트도 진행되지 않고 있고 취약점이 발견되어, 인테릴제이에서 경고문이 뜨고 있습니다.
<img width="888" alt="image" src="https://github.com/Katchup-dev/Katchup-server/assets/81692211/dfc9da75-4b7a-4ba8-9ef9-d15e38940d5b">

따라서 조금 시간이 걸리더라도 걷어내고, 다른 라이브러리로 교체 해야 할 것 같은데,
크게 두가지 대안이 있습니다.
1. [AWS SDK](https://aws.amazon.com/ko/sdk-for-java/)
2. [awspring](https://awspring.io/)  -> awspring 가이드 https://spring.io/projects/spring-cloud-aws

둘 중에 AWS에서 제공하는 SDK를 선택해서 리팩토링 하면 좋을 것 같은데 어떻게 생각하시나요?
@Seokyeong237 @yeseul106

**Comment by Seokyeong237** [comment]
넵 좋아요~! awsspring이 더 간단해 보이긴 하는데 더 편하신 걸로 교체하면 좋을 것 같습니다👍👍👍👍

**Comment by yeseul106** [comment]
네 !!! 좋습니다 ! 둘다 좋은 방법 같아서 제 생각에도 더 레퍼런스 많고 편하신걸로 하는게 좋을 것 같네요 !!
