### ISSUE TITLE
[FEAT] 회원탈퇴 API

### ISSUE THREAD

**Issue by Seokyeong237** [Katchup-dev/Katchup-server#152]
## 🥫 Issue 🥫

회원탈퇴 API를 구현하겠습니다.

## 🍔  Todo 🥤
- [x] 도메인 설계
- [x] API 구현

## 논의사항
회원탈퇴시 유저를 soft delete 해야 하는데요. 그래서 탈퇴하면 member 테이블의 is_deleted 값을 true로 변경합니다.
그런데 기획 측에서 회원탈퇴 일자로부터 몇 일이 지났는지를 알 수 있으면 좋을 것 같다고 하셔서 현재 두 가지 방식을 고민 중입니다.
1. member 테이블에 deletedAt 필드 추가해서 구분
2. withdraw 테이블에서 createdAt으로 구분

어떤 게 더 나은 것 같은지 의견부탁드립니다~! 갠적으로 필드명만 봤을 때 직관적인 건 1번이라고 생각하지만 또 다른 의견이 있을 거 같아서 여쭤봅니다 ㅎㅎㅎ

+ 개발을 하다보니, 탈퇴한 유저가 다시 로그인을 하면 1번의 경우에는 member의 is_deleted, deletedAt 두 필드를 모두 바꿔줘야 하지만, 2번의 경우에는 member의 is_deleted만 건드리면 되기 때문에 2번 방식이 더 나은 것 같네요..!

**Comment by yeseul106** [comment]
도메인의 영역(?)을 생각해서 분리한다면 탈퇴한 유저의 데이터는 withdraw로 넘겨서 해당 테이블에서 모두 관리를 하는 것이 추후 유지보수 할 때 개인적인 생각으로는 더 좋을 것 같긴 한데 ,,,!
필드명으로 봤을 때 서경님 말대로 Member 테이블에 deletedAt 필드로 관리하는 것도 좋을 것 같네요 !! 

+ 개발 하다보니 편한 부분을 발견했다면 그 방법으로 가지고 나가는게 가장 베스트 일것 같습니다 !
