### ISSUE TITLE
[FEAT] 로그아웃 api 개발

### ISSUE THREAD

**Issue by yeseul106** [Katchup-dev/Katchup-server#155]
## 🥫 Issue 🥫

- 로그아웃 api를 구현합니다.

## 🍔  Todo 🥤
- [ ] 로그아웃 api 구현

## ✏️  논의사항
제가 고민한 로그아웃의 로직은 아래 두 가지 경우와 같습니다.

1. 현재 RDBMS(Member 테이블)에 저장해놓는 refresh_token을 삭제 해주고, 이후 클라에서 로그인 api 요청이 왔을 때 access와 refresh 생성 후 재발급된 refresh를 저장하도록
2. 로그인 시, 생성된 refresh token은 redis에 저장을 해두고 관리하고 로그아웃 시 refresh를 black list 처리

사실 로그인을 통해 클라이언트로 발급한 토큰은 삭제만으로는 이미 발급받은 토큰을 유효하지 않게 처리할 수 없기 때문에 해당 토큰을 블랙 리스트 처리 하여 유저가 로그아웃을 했다면 그 토큰으로는 인증 처리를 거부할 수 있도록 2번 방법으로 개선하는게 좋다고 개인적으로는 생각하는 바입니다 !

하지만 현재 릴리즈까지 타이트한 일정 때문에 우선적으로 1번 방식으로 처리하고, 추후 리팩을 2번 방법으로 하는건 어떤지 의견 궁금해서 남깁니다 !
@Seokyeong237 @unanchoi

**Comment by unanchoi** [comment]
네 그렇게 진행하면 좋을 것. ㅏㅌ습니다

**Comment by Seokyeong237** [comment]
네엡~!! 추후 2번 방향으로 리팩토링하면 좋을 것 같습니다!
